import { Song, Artist, Album, Playlist, SubscriptionPlan } from './types';

export const mockSongs: Song[] = [
  {
    id: '1',
    title: 'Midnight Dreams',
    artist: 'Luna Wave',
    artistId: 'artist1',
    album: 'Neon Nights',
    albumId: 'album1',
    duration: 245,
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400',
    audioUrl: '',
  },
  {
    id: '2',
    title: 'Electric Heart',
    artist: 'Neon Pulse',
    artistId: 'artist2',
    album: 'Synthetic Love',
    albumId: 'album2',
    duration: 198,
    coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    audioUrl: '',
  },
  {
    id: '3',
    title: 'Digital Soul',
    artist: 'Luna Wave',
    artistId: 'artist1',
    album: 'Neon Nights',
    albumId: 'album1',
    duration: 312,
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400',
    audioUrl: '',
  },
  {
    id: '4',
    title: 'Cyber Love',
    artist: 'Synth Master',
    artistId: 'artist3',
    album: 'Future Bass',
    albumId: 'album3',
    duration: 267,
    coverImage: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400',
    audioUrl: '',
  },
  {
    id: '5',
    title: 'Neon Lights',
    artist: 'Neon Pulse',
    artistId: 'artist2',
    album: 'Synthetic Love',
    albumId: 'album2',
    duration: 223,
    coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    audioUrl: '',
  },
];

export const mockArtists: Artist[] = [
  {
    id: 'artist1',
    name: 'Luna Wave',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    followers: 1250000,
    bio: 'Luna Wave is an electronic music producer known for blending ambient soundscapes with driving beats.',
    topSongs: mockSongs.filter(s => s.artistId === 'artist1'),
    albums: [],
  },
  {
    id: 'artist2',
    name: 'Neon Pulse',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    followers: 890000,
    bio: 'Creating the soundtrack for the future, one beat at a time.',
    topSongs: mockSongs.filter(s => s.artistId === 'artist2'),
    albums: [],
  },
  {
    id: 'artist3',
    name: 'Synth Master',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
    followers: 2100000,
    bio: 'Pioneer of futuristic electronic music with a retro twist.',
    topSongs: mockSongs.filter(s => s.artistId === 'artist3'),
    albums: [],
  },
  {
    id: 'artist4',
    name: 'Bass Queen',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    followers: 1650000,
    bio: 'Queen of the bass drops and heavy electronic beats.',
    topSongs: [],
    albums: [],
  },
];

export const mockAlbums: Album[] = [
  {
    id: 'album1',
    title: 'Neon Nights',
    artist: 'Luna Wave',
    artistId: 'artist1',
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400',
    releaseYear: 2024,
    songs: mockSongs.filter(s => s.albumId === 'album1'),
  },
  {
    id: 'album2',
    title: 'Synthetic Love',
    artist: 'Neon Pulse',
    artistId: 'artist2',
    coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    releaseYear: 2023,
    songs: mockSongs.filter(s => s.albumId === 'album2'),
  },
  {
    id: 'album3',
    title: 'Future Bass',
    artist: 'Synth Master',
    artistId: 'artist3',
    coverImage: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400',
    releaseYear: 2024,
    songs: mockSongs.filter(s => s.albumId === 'album3'),
  },
  {
    id: 'album4',
    title: 'Quantum Beats',
    artist: 'Luna Wave',
    artistId: 'artist1',
    coverImage: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400',
    releaseYear: 2023,
    songs: [],
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: 'playlist1',
    title: 'Chill Vibes',
    coverImage: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400',
    songCount: 25,
    songs: mockSongs,
    description: 'Perfect playlist for relaxing and unwinding',
  },
  {
    id: 'playlist2',
    title: 'Workout Energy',
    coverImage: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400',
    songCount: 30,
    songs: mockSongs,
    description: 'Get pumped with these energetic beats',
  },
  {
    id: 'playlist3',
    title: 'Night Drive',
    coverImage: 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=400',
    songCount: 20,
    songs: mockSongs,
    description: 'Late night driving music',
  },
  {
    id: 'playlist4',
    title: 'Focus Flow',
    coverImage: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=400',
    songCount: 40,
    songs: mockSongs,
    description: 'Music to help you concentrate',
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    features: [
      'Ad-supported listening',
      'Standard audio quality',
      'Shuffle play only',
      'Limited skips',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 9.99,
    features: [
      'Ad-free listening',
      'High quality audio',
      'Unlimited skips',
      'Download songs',
      'Offline mode',
    ],
    recommended: true,
  },
  {
    id: 'family',
    name: 'Family',
    price: 14.99,
    features: [
      'All Premium features',
      'Up to 6 accounts',
      'Family mix playlist',
      'Parental controls',
      'Ad-free for everyone',
    ],
  },
];
